### ISSUE TITLE
Error during installation with OCAML v 4.10.0

### ISSUE THREAD

**Issue by sarah-robinson** [UnixJunkie/fragger#3]
Hello,
I am trying to install your package on OSX, and am seeing some errors during installation.
I have new installations of OCaml and OPAM, and when I git clone and run ./build.sh I see the following errors:

```
+ /Users/sarah/.opam/default/bin/ocamlfind ocamlc -c -w +27 -annot -thread -g -annot -bin-annot -package batteries -package core -package dolog -package parmap -package str -o my_utils.cmo my_utils.ml
File "my_utils.ml", line 87, characters 12-20:
87 |   let out = open_out f in
                 ^^^^^^^^
Alert deprecated: Core.open_out
[since 2016-04] Use [Out_channel.create]
File "my_utils.ml", line 88, characters 5-9:
88 |   if head <> "" then P.fprintf out "%s" head;
          ^^^^
Error: This expression has type string but an expression was expected of type
         Core_kernel.Int.t = int
Command exited with code 2.
E: Failure("Command ''/Users/sarah/.opam/default/bin/ocamlbuild' bb_atom_quads.native get_frag.native query.native -tag debug  -classic-display -cflags '-w +27',-annot,-thread -lflag -thread ' terminated with error code 10")
make: *** [build] Error 1
```

I have put the full output from the ./build.sh command into an attached file, and have also attached a text file containing the version numbers of all of my opam packages. Any help with this issue would be much appreciated.

Best wishes,
Sarah

[opam_lib_versions.txt](https://github.com/UnixJunkie/fragger/files/4624310/opam_lib_versions.txt)
[fragger_error.txt](https://github.com/UnixJunkie/fragger/files/4624330/fragger_error.txt)

**Comment by UnixJunkie** [comment]
Try with an older ocaml version, like 4.05.0.
```
opam switch create 4.05.0
```
Note that fragger uses a script from CCP4 (pdbset), so you will need the CCP4 suite to be installed
at some point.

**Comment by sarah-robinson** [comment]
Thank you!

I've done that, and installed the CCP4 suite, and I get past the utils line. I then get the following error:

```
+ /Users/sarah/.opam/4.05.0/bin/ocamlfind ocamlc -c -w +27 -annot -thread -g -annot -bin-annot -package batteries -package core -package dolog -package parmap -package str -o bb_atom_quads.cmo bb_atom_quads.ml
File "bb_atom_quads.ml", line 18, characters 5-8:
Error: Unbound module Log
Command exited with code 2.
```

I'm very new to ocaml, so thanks for your help!

[fragger_error2.txt](https://github.com/UnixJunkie/fragger/files/4627429/fragger_error2.txt)

**Comment by UnixJunkie** [comment]
The dolog library needs to be installed.
```
opam install dolog.1.1
```
of dolog.2.0 or dolog.3.0

I am not sure which one is compatible with fragger

**Comment by sarah-robinson** [comment]
Perfect, thank you very much! It worked with dolog.1.1.

**Comment by UnixJunkie** [comment]
If you want to help with Fragger, removing the dependency on CCP4 would be nice.
In that case, I could create a fully automatic self-installer for Fragger.
I do not use it anymore, but there is an active researcher in Toulouse using it (David Simoncini).
I am OK to maintain Fragger, but I don't do new developments in it.

**Comment by UnixJunkie** [comment]
cf. https://github.com/UnixJunkie/fragger/issues/4 if you are interested.
A python or awk script could do the job.
No need to known OCaml.
